config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  mount ContactUs::Engine, :at => '', as: 'contact'
  mount InyxCatalogueRails::Engine, :at => '', as: 'catalogues'
  
  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]
  scope :admin do
  	resources :users do
  		collection do
  			get '/angular_index', to: 'users#angular_index'
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :moderador
    elsif user.has_role? :redactor
    end
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
	validate :ip_per_date

	def self.add(remote_ip)
		location = Geocoder.search(remote_ip).first
		unless location.nil?
			Location.create ip: remote_ip, country_code: location.country_code, country: location.country, latitude: location.latitude, longitude: location.longitude
		end
	end
	
	private
	
	def ip_per_date
		if Location.where(ip: self.ip).count > 0 && Location.where(ip: self.ip).order("created_at DESC").first.created_at.to_date == DateTime.now.to_date
			errors.add(:ip, 'ip validada')
		end
	end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  validates_presence_of :name, :role_ids
  
	#has_many :posts, dependent: :destroy relation posts
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

  def self.user_json(current_user)
    json = []
    User.where("id != #{current_user.id}").order('created_at DESC').each do |user|
      u = user.as_json 
      u.merge!({rol: user.roles.first.id })
      json.push u
    end
    json.as_json
  end
  
  def self.group_by_roles
    rtrn = {}
    [:admin, :moderator, :redactor].each do |rol|
      rtrn[rol] = User.with_role(rol).count
    end
    rtrn
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :authenticate_user!
	layout 'admin/application'
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.admin_index_path, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end

  def layout_by_resource
    if devise_controller? 
      "admin/application"
    else
      "application"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'

  def index
    authorize! :index, @user, :message => "#{t('cancan.messages.access_denied')} #{t('models.user')}"
  end

  def angular_index
    users = User.user_json(current_user)
    respond_to do |format|
      format.html
      format.json { render :json => users  }
    end
  end

  def new
    authorize! :new, @user, :message => "#{t('cancan.messages.access_denied')} #{t('models.user')}"
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    unless current_user.has_role? :admin
      redirect_to :back, :alert => t("notification.denied")
    end
  end

  def edit
    authorize! :update, @user, :message => "#{t('cancan.messages.access_denied')} #{t('models.user')}"
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => "#{t('cancan.messages.access_denied')} #{t('models.user')}"

    @user = User.find(params[:id])

    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to users_path, :notice => t("notification.update") }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    authorize! :create, @user, :message => "#{t('cancan.messages.access_denied')} #{t('models.user')}"
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.add_role Role.find(user_params[:role_ids]).name
        format.html { redirect_to users_path, notice: t("notification.create") }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @user, :message => "#{t('cancan.messages.access_denied')} #{t('models.user')}"
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => t("notification.delete")
    else
      redirect_to users_path, :notice => t("notification.un_delete")
    end
  end
    
  def delete
    authorize! :destroy, @user, :message => "#{t('cancan.messages.access_denied')} #{t('models.user')}"
    User.destroy( redefine_destroy params[:ids].split(",") )
    respond_to do |format|
      format.json { redirect_to users_path, notice: t("notification.delete") }
    end
  end

  private

  #metodo para redefinir el array de los elementos selecionados que se van a eliminar
  def redefine_destroy(params)
    params.sort.each do |id|
      params.delete id unless User.exists? id
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role_ids, :encrypted_password)
  end

  

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
		Location.add(request.remote_ip)
		@catalogo = InyxCatalogueRails::Catalogue.where(public: true)
		datos= @catalogo
		seccion = 3
		items = datos.count
		residuo = datos.count.modulo(seccion)
		secciones = residuo > 0 ? (items/seccion)+1 : items/seccion
		@catalogos = {}
		secciones.times do |x|
			@catalogos[x] = datos[0...seccion]
			datos = datos.drop(seccion)
		end
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.haml
= content_for(:title, "Admin - Dashboard")
%div{ style: "padding:30px; padding-bottom:30px; padding-top:0px;"}
	- flash.each do |name, msg|
		- if msg.is_a?(String)
			%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
				%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
				= content_tag :div, msg, :id => "flash_#{name}"
	.row
		.col-lg-3.col-md-6.col-sm-6
			.panel-info		
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= Location.all.count
						.title-info
							Visitas
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-eye
		.col-lg-3.col-md-6.col-sm-6
			.panel-info
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= User.all.count
						.title-info
							Usuarios
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-users
		.col-lg-3.col-md-6.col-sm-6
			.panel-info
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info#hora
							= User.all.count
						.title-info
							Usuarios
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-clock-o
		.col-lg-3.col-md-6.col-sm-6
			.panel-info
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= DateTime.now.strftime("%d")
						.title-info
							= DateTime.now.strftime("%B")
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-calendar
	.row	
		.col-lg-12.col-md-12.col-sm-12
			.panel-info2
				= area_chart Location.group_by_day(:created_at, format: "%b %d'%y").count, discrete: true, library: { backgroundColor: "none",  hAxis: { title: 'Días', titleTextStyle: { color: '#c0c0c0', italic: false }, textStyle: { color: '#c0c0c0' } }, vAxis: { title: 'Visitas', titleTextStyle: { color: '#c0c0c0', italic: false }, textStyle: { color: '#c0c0c0' } }, colors: ['#F4DD5A'] } 	
				
		.col-lg-6.col-md-6.col-sm-12
			.panel-info2{ style: "padding-top: 15px; margin-right:-8px;" }
				= geo_chart Location.group(:country).count, library: { backgroundColor: "none", colors: ['#FFBF00'] }
		.col-lg-6.col-md-6.col-sm-12
			.panel-info2
				= pie_chart User.group_by_roles	, library: { backgroundColor: "none"}
		.col-lg-12.col-md-12.col-sm-12
			.panel-info2
				= line_chart User.group_by_day(:created_at, format: "%b %d'%y").count, discrete: true, library: { backgroundColor: "none",  hAxis: { title: 'Días', titleTextStyle: { color: '#c0c0c0', italic: false }, textStyle: { color: '#c0c0c0' } }, vAxis: { title: 'Nuevos Usuarios', titleTextStyle: { color: '#c0c0c0', italic: false }, textStyle: { color: '#c0c0c0' } }, colors: ['#F4DD5A'] } 	

%footer{style:"padding-bottom:20px;"}
	%center
		Todos los derechos reservados. Desarrollado por 
		%span{style: "font-size:18px;font-family:'Arial Black';color:#FFBA3D;font-style:oblique;"}
			Inyxtech 

app/views/contact_us/contact/index.html.haml
= content_for(:title, "Parcatur - Contacto")
%section.contact_us
	.container
		%h1
			%i.fa.fa-phone-square
			%strong Contacto
			%small.hidden-xs Toda la información necesaria para contactárnos.
		%hr

		.col-lg-4.col-md-4.col-sm-6.col-xs-12
			.widget{style: "margin-top:5px;"}
				.widget-header
					%h4 Formulario de contacto
				.content-widget
					= form_tag({controller: "contact", action: "send_contact_message", method: "post"}, {class: "contact_form"}) do
						= text_field_tag :name, "", :class=>'form-control', :type => "text", :placeholder=>'Nombre', style: 'margin-bottom: 10px;'
						= text_field_tag :email, "", :class=>'form-control', :type => "text", :placeholder=>'Email', style: 'margin-bottom: 10px;'
						= text_area_tag :comment, "", :class=>'form-control' , :placeholder=>'Mensaje', style: 'margin-bottom: 10px; height: 80px;'
						#recaptcha_widget{:style => "display:block"}
							#recaptcha_image
							.input-group{ style:'margin-top: 5px; margin-bottom:10px;'}
								= text_field_tag :recaptcha_response_field, "",type: "text", id: "recaptcha_response_field", class: "form-control", placeholder: "Captcha"
								%span.input-group-btn
									= button_tag "<i class='fa fa-refresh'></i>".html_safe, :type => "button", class: "form-control", :onclick => "javascript:Recaptcha.reload(); return false;"
						= raw recaptcha_tags :display => { :theme => 'custom', lang: 'es' }, ajax: true
						= button_tag(type: 'submit', class: "btn btn-info", style:"width:100%") do
							%i.fa.fa-envelope.fa-2x
		

app/views/contact_us/contact/messages.html.haml
= content_for(:title, "Admin - Mensajes")
.angular{'ng-controller'=>'indexCtrl',  'ng-init'=>"init()", style:"padding:30px;padding-bottom:0px;"}
  .form-inline
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-search
        %input#input-search{"ng-model" => "buscar.$", :placeholder => t("contact.actions.search"), :type => "text"} 
  .alert{class: 'alert-{{statusAlert}}', 'ng-show'=>"alert==true"} 
    %strong Admin:    
    {{msnAlert}}
    %a.close-alert.pull-right{href: "", "ng-click" => "alertClose()"} ×


  = render 'layouts/admin/messages' 
  %br

  .panel.panel-default
    .panel-heading
      %button.btn.btn-danger.hidden-xs{:disabled =>"", 'ng-show'=>"count>0" }
        %i.fa.fa-envelope        
        {{count}}
      %button.btn.btn-default.hidden-xs{:disabled =>"", 'ng-show'=>"count==0"}
        %i.fa.fa-envelope        
        {{count}}
      %button.btn.btn-default{"ng-click" => "refresh()", :title => t("contact.actions.refresh")}
        %i.fa.fa-refresh#icon-refresh
      %a.btn.btn-default{"ng-show" => "messages.data.length", "ng-click" => "allSelected(messages)", :title => t("contact.actions.all_messages")}
        %i.fa.fa-check-square-o
      %button#btn-delete.btn.btn-default{class: "btn-{{btnDelete}}", "ng-click" => "destroy()", :title => t("contact.actions.delete_all_messages")}
        %i.fa.fa-trash-o       
      %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000"}
        = t('contact.actions.page') 
        {{page}}
      %button.btn.btn-default.pull-right{"ng-click" => "nextList();"}
        %i.fa.fa-arrow-right
      %button.btn.btn-default.pull-right{"ng-click" => "lastList();"}
        %i.fa.fa-arrow-left
    .panel-body
      %table{:style => "width:100%"}
        %tbody
          %tr.row-message{class: "select-{{message.checked}}", :id => "row-{{message.id}}", "ng-repeat" => "message in messages.data | filter:buscar | interval:interval_a:interval_b" }
            %td.messages{class: " read-{{message.read}}", :style => "width: 1%;"}
              %input.check{class: "check-style", :id => "check-{{message.id}}", "ng-click" => "selected(message.id);$event.stopPropagation();", :type => "checkbox", "ng-model"=>"message.checked"}
            %td.messages.hidden-xs{class: " read-{{message.read}}", :style => "width: 1%;"}
              %i.fa.fa-envelope{'ng-if'=>"message.read == false"}
              %i.fa.fa-file-text-o{'ng-if'=>"message.read == true"}
            %td.messages{class: " read-{{message.read}}"}
              %a{href:"/admin/messages/{{message.id}}"}

                {{ message.name }}  
            %td.messages.hidden-xs.hidden-sm.hidden-md{ class: "read-{{message.read}}", :style => "width: 60%;"}
              {{ message.email }}  
            %td.messages{class: " read-{{message.read}}"}
              %center
                {{ message.created_at | date}}
                %span.hidden-xs - {{ message.created_at | date:'HH:mm'}}  
          %tr{"ng-show" => "!messages.data.length"}
            %td{:style => "width:100%"}
              %center
                %i.fa.fa-frown-o
                = t('contact.actions.empty')
    .panel-footer
      %center
        %b
          {{messages.data.length}} 
        = t('contact.messages_cont')

app/views/contact_us/contact/show_message.html.haml
= content_for(:title, "Admin - #{@message.email}")
.angular{'ng-controller'=>'showCtrl','ng-init'=>"init()",  style:"padding:30px;;padding-bottom:0px;"}
  .form-inline
  %a.btn.btn-default{href: "/admin/messages", :title => t("contact.actions.inbox")}
    %i.fa.fa-inbox
  %button#msn-delete.btn.btn-default{"ng-click" => "destroy(#{@message.id})", :title => t("contact.actions.delete_message")}
    %i.fa.fa-trash-o
  %br
  %br
  .panel.panel-default        
    .panel-heading
      %b
      %i.fa.fa-envelope
        = @message.email
    .panel-body
      .row
        .col-lg-10
          %h2 
            = @message.name
          = @message.email
          %br/
          = @message.created_at.strftime("%B %d, %Y")
          %br/
          = @message.created_at.strftime("%H:%M")
        .col-lg-2{style:"font-size:120px;color:#F2F2F2;"}
          %i.fa.fa-envelope-o.hidden-xs.hidden-sm.hidden-
      %hr   
      %p{style:"font-size:18px; text-align:justify;"}
        = @message.message
    .panel-footer

app/views/inyx_catalogue_rails/catalogues/_form.html.haml
= simple_form_for(@catalogue) do |f|  
  .panel.panel-default
    .panel-heading
      %i.fa.fa-th-list
        Nuevo Item
    .panel-body
      .form-inputs
        .field
          %br/
          = f.input :image, label: false, as: :file, input_html: { class: 'form-control', placeholder: t('catalogues.new.image')}
        .field
          %br/
          = f.input :title, label: false, input_html: { class: 'form-control', placeholder: "Titulo"}
        .field
          %br/
          = f.input :description, as: :text, label: false, input_html: { class: 'form-control', placeholder: "Descripción", :rows => 8 }           
        .field
          %br/
          = f.association :category_catalogue, label: false, prompt: "Tipo de Catalogo", input_html: { class: 'form-control'}
        .field
          %br/
          ¿Deseas publicarlo?
          = f.check_box :public, label: false
        .field
          %br/
          = f.input :prince, label: false, input_html: { class: 'form-control', value: "0", style:"opacity:0"}   
      %br/
    .panel-footer
      .form-actions
        = f.button :submit, "Guardar", class: "pull-right btn btn-warning"
      .clearfix

app/views/inyx_catalogue_rails/catalogues/edit.html.haml
%div{ style: "padding:30px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_catalogue_rails/catalogues/index.html.haml
= content_for(:title, "Admin - Catálogo")

%div{'ng-controller'=>'indexCatalogueCrtl',  'ng-init'=>'init()', style:"padding:30px;padding-bottom:0px;"}
  .angular
    .form-inline
      .form-group
        .input-group
          .input-group-addon
            %i.fa.fa-search
          %input#input-search{"ng-model" => "buscar.$", :placeholder => "Buscar...", :type => "text"}  
    .alert{class: 'alert-{{statusAlert}}', 'ng-show'=>"alert==true"} 
      %strong Admin:    
      {{msnAlert}}
      %a.close-alert.pull-right{href: "", "ng-click" => "alertClose()"} ×
    = render 'layouts/admin/messages'
    %br/
    .panel.panel-default
      .panel-heading
        = link_to new_catalogue_path, class: "btn btn-default", title: t("admin.buttons.new") do
          %i.fa.fa-plus-circle
        
        %button.btn.btn-default.hidden-xs{"ng-click" => "refresh()", :title => t("catalogues.actions.refresh")}
          %i.fa.fa-refresh#icon-refresh
        %a.btn.btn-default.hidden-xs{"ng-show" => "products.data.length", "ng-click" => "allSelected(products)", :title => t("catalogues.actions.select_all")}
          %i.fa.fa-check-square-o
        %button#btn-delete.btn.btn-default.hidden-xs{class: "btn-{{btnDelete}}", "ng-click" => "destroy()", :title => t("catalogues.actions.delete_all")}
          %i.fa.fa-trash-o
        %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000"}
          =t("catalogues.actions.page") 
          {{page}} 
        %button.btn.btn-default.pull-right{"ng-click" => "nextList();"}
          %i.fa.fa-arrow-right
        %button.btn.btn-default.pull-right{"ng-click" => "lastList();"}
          %i.fa.fa-arrow-left
      .panel-body
        %table{style: "width:100%"}
          %tbody
            %tr{ class: "select-{{product.checked}}", :id => "row-{{product.id}}", "ng-repeat" => "product in products.data | filter:buscar | interval:interval_a:interval_b "}
              %td.messages{width: "1px;"}
                %input.check{:id => "check-{{product.id}}", "ng-click" => "selected(product.id); $event.stopPorpagation();", :type => "checkbox", "ng-model" => "product.checked"}
              %td.messages{'ng-if'=>'product.public == true'}
                %i.fa.fa-check-circle-o{style:"font-size: 20px;"}   
              %td.messages{'ng-if'=>'product.public == false'}
                %i.fa.fa-times-circle-o{style:"font-size: 20px;"}            
              %td.messages
                = link_to "/admin/catalogues/{{product.id}}" do
                  {{product.title}}
              %td.messages.hidden-xs
                {{product.description.slice(0,50)+"..."}}
              %td.messages.hidden-xs
                {{product.category.title}}
              %td.messages.hidden-xs
                = link_to "/admin/catalogues/{{product.id}}", title: t('admin.actions.show') do
                  %i.fa.fa-exclamation-circle
                = link_to "/admin/catalogues/{{product.id}}/edit", title: t('admin.actions.edit') do
                  %i.fa.fa-edit
                = link_to "/admin/catalogues/{{product.id}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' } do
                  %i.fa.fa-trash-o

            %tr{"ng-show" => "!products.data.length"}
              %td{:style => "width:100%"}
                %center
                  %i.fa.fa-frown-o
                  = t("catalogues.actions.empty")
              
      .panel-footer

app/views/inyx_catalogue_rails/catalogues/index_front.html.haml
.container{'ng-controller'=>'indexCatalogueCrtl','ng-init'=>'init()',}
	.form-inline
		.form-group
		.input-group
			.input-group-addon
				%i.fa.fa-search
			%input#input-search{"ng-model" => "buscar.$", :placeholder => t("catalogues.actions.search"), :type => "text"}
	%br
	%br 
		.row
			%div{"ng-repeat" => "product in products.data | filter:buscar"}
				.col-lg-4.col-md-4.col-sm-6{'ng-if'=>'product.public == true'}
					%a.thumbnail{href: "/catalogues/{{product.id}}"}
						%img.img-responsive{src:"{{product.image.url}}", style: "height:280px"}
						.caption
							%h3
								{{product.title}}
							.label.label-primary
								%i.fa.fa-tag
								{{product.category.title}}
				

app/views/inyx_catalogue_rails/catalogues/new.html.haml
%div{ style: "padding:30px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_catalogue_rails/catalogues/show_front.html.haml
.header-perfil.hidden-xs
.sector-perfil
	#title-speakers.visible-xs
		%p{style:"margin-bottom: 0px;"} Speakers  
		%p inspiradores
	#text-speakers.visible-xs
		%p{style:"margin-bottom: 0px;"} Se parte de nuestro selecto grupo 
		%p de speakers internacionales certificados.
	.subsection-perfil{style:"background-image:url(#{@product.image})"}
	.subsection-info
		.container#container-fluid
			.col-lg-4.col-md-4.col-sm-6
				.speaker-selector
					.speaker{style:"background-image: url(#{@product.image})"}
			.col-lg-8.col-md-8.col-sm-6
				%h3
					= @product.title
				%p{align:"justify", style:"color:#6D6D6D;"}
					= @product.description

	
			

app/views/users/edit.html.haml
= content_for(:title, "Admin - Usuarios | Editar")
%div{ style: "padding:30px; padding-bottom:0px;"}
	= render 'form'

app/views/users/index.html.haml
= content_for(:title, "Admin - Usuarios")

%div{'ng-controller'=>'indexUserCtrl',  'ng-init'=>'init()', style:"padding:30px;padding-bottom:0px;"}
	.angular
		.form-inline
			.form-group
				.input-group
					.input-group-addon
						%i.fa.fa-search
					%input#input-search{"ng-model" => "buscar.$", :placeholder => t("admin.user.actions.search"), :type => "text"} 
		.alert{class: 'alert-{{statusAlert}}', 'ng-show'=>"alert==true"} 
			%strong Admin:    
			{{msnAlert}}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
		= render 'layouts/admin/messages'

		%br/
		.panel.panel-default
			.panel-heading
				= link_to new_user_path, class: "btn btn-default", title: t("admin.buttons.new") do
					%i.fa.fa-plus-circle
				%button.btn.btn-default{"ng-click" => "refresh()", :title => t("admin.buttons.refresh") }
					%i.fa.fa-refresh#icon-refresh
				%a.btn.btn-default{"ng-show" => "users.data.length", "ng-click" => "allSelected(users)", :title => t("admin.buttons.select_all") }
					%i.fa.fa-check-square-o
				%button#btn-delete.btn.btn-default{class: "btn-{{btnDelete}}", "ng-click" => "destroy()", :title => t("admin.buttons.trash") }
					%i.fa.fa-trash-o
				%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000"}
					Página {{page}}
				%button.btn.btn-default.pull-right{"ng-click" => "nextList();"}
					%i.fa.fa-arrow-right
				%button.btn.btn-default.pull-right{"ng-click" => "lastList();"}
					%i.fa.fa-arrow-left
			.panel-body
				%table{style: "width:100%"}
					%tbody
						%tr{ class: "select-{{user.checked}}", "ng-click" => "show(user.id)", :id => "row-{{user.id}}", "ng-repeat" => "user in users.data | filter:buscar | interval:interval_a:interval_b "}
							%td.messages{width: "1px;"}
								%input.check{:id => "check-{{user.id}}", "ng-click" => "selected(user.id); $event.stopPorpagation();", :type => "checkbox", "ng-model" => "user.checked"}
							%td.messages {{user.name}}
							%td.messages.hidden-xs {{ user.email }}
							%td.messages.hidden-xs {{ roles[user.rol] }}
							%td.messages
								%a{"data-toggle" => "modal", :href => "#role-options-{{user.id}}", :type => "button"}= t("user.change-rol")
							%td.messages
								= link_to "/admin/users/{{user.id}}", title: t('admin.actions.show') do
									%i.fa.fa-exclamation-circle
								= link_to "/admin/users/{{user.id}}/edit", title: t('admin.actions.edit') do
									%i.fa.fa-edit
								= link_to "{{destroy_path(user.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' } do
									%i.fa.fa-trash-o
								= render "modal_role"
						%tr{"ng-show" => "!users.data.length"}
							%td{:style => "width:100%"}
								%center
									%i.fa.fa-frown-o
									No hay Usuarios.

							
			.panel-footer